### ISSUE TITLE
Track ECMAScript Temporal Proposal

### ISSUE THREAD

**Issue by thomasfoster96** [thomasfoster96/literary-react#1]
Once the [Temporal](https://github.com/tc39/proposal-temporal) proposal is finished, the `DateTime`, `Date` and `Time` components should ideally switch to preferring `CivilDateTime`, `CivilDate` and `CivilTime` over the old `Date` class.

### Tasks:
- [ ] Warn about passing `Date` objects.
- [ ] Deal with `Instant` and `ZonedInstant`.
- [ ] Eventually drop support for `Date` objects entirely.

### Questions:
* What to do with `Instant` and `ZonedInstant`?
